config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "candidates#index"
  resources :candidates
  resources :registrations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    enum :status, [:undecided, :hell_no, :not_a_fit, :on_the_fence, :shows_promise, :strong_contender, :hire_this_person]
    has_rich_text :notes
    has_one_attached :resume
    has_one_attached :cover_letter
    validates :name, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  allow_unauthenticated_access
  before_action :set_candidate, only: %i[ show edit update ]
  def index
    @candidates = Candidate.order(status: :desc)
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      redirect_to @candidate
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @candidate.update(candidate_params)
      redirect_to @candidate
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @candidate.destroy
    redirect_to candidates_path
  end

  private
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    def candidate_params
      params.expect(candidate: [ :name, :notes, :phone, :email, :status, :resume, :cover_letter ])
    end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  allow_unauthenticated_access

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to root_path, notice: 'Account successfully created.'
    else
      flash[:alert] = @user.errors.full_messages.join("\n")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/candidates/_form.html.erb
<%= form_with model: candidate do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div>
    <%= form.label :phone %>
    <%= form.telephone_field :phone %>
  </div>
  <div>
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>
<div>
<%= form.label :status %>
<%= form.select :status, Candidate.statuses.keys.map { |s| [s.humanize, s] }, 
               { class: "form-control" } %>
</div>
<div>
<%= form.label :resume, style: "display: block" %>
<%= form.file_field :resume, accept: ".pdf,.doc,.docx,.txt,.rtf,.odt" %>
</div>
<div>
<%= form.label :cover_letter, style: "display: block" %>
<%= form.file_field :cover_letter, accept: ".pdf,.doc,.docx,.txt,.rtf,.odt" %>
</div>
    <div class="form-button">
      <%= form.submit %>
    </div>
  <% end %>

app/views/candidates/_status.html.erb
<%= form_with(model: candidate, html: { class: "inline-edit-form" }) do |form| %>
    <%= turbo_frame_tag "candidate_status_#{candidate.id}" do %>
      <div class="field inline-status-field">
        <%= form.select :status, 
                       Candidate.statuses.keys.map { |s| [s.humanize, s] },
                       {}, 
                       { class: "form-control", onchange: "this.form.requestSubmit()" } %>
      </div>
    <% end %>
  <% end %>
  

app/views/candidates/edit.html.erb
<h1>Edit Candidate</h1>
<div class="container">
<%= render "form", candidate: @candidate %>
<%= link_to "Cancel", @candidate %>
</div>

app/views/candidates/index.html.erb
<h1>Candidates</h1>
<div id="add-candidate">
<%= button_to "Add Candidate", new_candidate_path, method: :get, class: "big-button" %>
</div>
<div id="candidates">
<% @candidates.each do |candidate| %>
    <div class="candidate-container">
    <%= link_to "", candidate, class: "candidate-link" %>
    <div class="candidate-name">
    <%= candidate.name %>
    </div>
    <div class="candidate-status">
    <%= turbo_frame_tag "candidate_status" do %>
        <%= render 'status', candidate: candidate %>
      <% end %>
    </div>
    </div>
    <% end %>
</div>

app/views/candidates/new.html.erb
<h1>Add Candidate</h1>
<div class="container">
<%= render "form", candidate: @candidate %>
</div>
<%= link_to "Cancel", candidates_path %>

app/views/candidates/show.html.erb
<div class="flex-wrapper">
<h1 class="candidate-show-name"><%= @candidate.name %></h1>
<div class="candidate-buttons-container">
<button id="edit-button"><%= link_to "Edit", edit_candidate_path(@candidate) %></button>
<%= button_to "Delete", @candidate, method: :delete, class: "delete-button", data: { turbo_confirm: "Are you sure?" } %>
</div>
</div>
<div class="container">
<div class="candidate-status-section">
  <strong>Status:</strong>
  <%= turbo_frame_tag "candidate_status" do %>
    <%= render 'status', candidate: @candidate %>
  <% end %>
</div>
<div id="candidate-info">
    <div id="candidate-phone"><%= @candidate.phone %></div>
    <div id="candidate-email"><%= @candidate.email %></div>
    <% if @candidate.resume.attached? %>
    <div id="candidate-resume">
    <strong>Resume:</strong>
    <%= link_to "Download", rails_blob_path(@candidate.resume, disposition: "attachment") %>
    </div>
    <% end %>
    <% if @candidate.cover_letter.attached? %>
    <div id="candidate-cover-letter">
    <strong>Cover Letter:</strong>
    <%= link_to "Download", rails_blob_path(@candidate.cover_letter, disposition: "attachment") %>
    </div>
    <% end %>
</div>
<div id="candidate-notes">
<%= form_with model: @candidate do |form| %>
    <div>
    <%= form.label :notes, style: "display: block; font-weight: bold" %>
    <%= form.rich_text_area :notes %>
  </div>
    <div class="form-button">
      <%= form.submit "Save" %>
    </div>
  <% end %>
</div>
</div>
<%= link_to "Back", candidates_path, class: "alt-link" %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "HirePurpose" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
  <div id="logo"><%= link_to root_path do %>
    <%= image_tag "HirePurposeLogo.svg", alt: "Logo for HirePurpose" %>
    <% end %>
    </div>
  <nav>
  <ul class="navbar-nav">
   <li> <%= link_to "Home", root_path %> </li>
        <% if authenticated? %>
          <li class="nav-item">
            <%= button_to "Log out", session_path, method: :delete, class:"logout-button" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_session_path %>
          </li>
        <% end %>
      </ul>
</nav>
</header>
  <body>
    <%= yield %>
  </body>
  <footer>© 2025 Autumn Willard. All rights reserved.</footer>
</html>